[package]
name = "registry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-schema =  { workspace = true }
cosmwasm-std = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
bech32 = { workspace = true }
serde-json-wasm = { workspace = true }
serde-cw-value = { workspace = true }
sha2 = "0.10.6"
hex = "0.4.3"
schemars = { workspace = true }
osmosis-std = { workspace = true }
osmosis-std-derive = "0.13.2"
prost = {version = "0.11.2", default-features = false, features = ["prost-derive"]}
itertools = {workspace = true}
