# Verify that generated code is up-to-date.
#
# Note that we run these checks regardless whether the input files have
# changed, because generated code can change in response to toolchain updates
# even if no files in the repository are modified.
name: Check generated code

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-proto:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # we need a .git directory to run git diff
      -
        name: Get git diff
        uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            proto/**
            **/**.pb.go
            **/client/**.go
            scripts/ci/**
            Makefile
            Dockerfile
            .github/workflows/check-generated.yml
      - 
        name: üêø Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
      -
        name: "Check protobuf generated code"
        run: scripts/ci/check-generated.sh
