# Verify that generated protobuf code is up-to-date.
#
# Note that we run these checks regardless whether the input files have
# changed, because generated code can change in response to toolchain updates
# even if no files in the repository are modified.

name: Check generated protobuf code
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'proto/**'
      - '**/**.proto'
      - '**/**.pb.go'
      - '**/**.sum'
      - '**/client/**.go'
      - 'scripts/ci/**'
      - 'Makefile'
      - 'Dockerfile'
      - '.github/workflows/check-generated.yml'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-generated-protobuf:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      -
        name: "Check protobuf generated code"
        run: |
          make proto-all
          make run-querygen
      - 
        name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *.go
          git add *.proto
          git commit -m "Generated protofile changes" || echo "No changes to commit"
          git push
