# Verify that generated code is up-to-date.
#
# Note that we run these checks regardless whether the input files have
# changed, because generated code can change in response to toolchain updates
# even if no files in the repository are modified.
name: Check generated code
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1  # we need a .git directory to run git diff

      - name: "Check protobuf generated code"
        run: contrib/scripts/check-generated.sh
        shell: bash
        with:
          password: ${{ secrets.ADD_TO_PROJECT_PAT }}