# Ensure that generated code is up-to-date.
name: Generate protobuf code

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "proto/**"
      - "**/**.proto"
      - "**/**.pb.go"
      - "**/**.sum"
      - "**/client/**.go"
      - "scripts/ci/**"
      - "Makefile"
      - "Dockerfile"
      - ".github/workflows/check-generated.yml"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: "Check protobuf generated code"
        run: |
          chmod +x ./scripts/protocgen.sh
          make proto-all
          make run-querygen
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *.go
          git add *.proto
          git commit -m "Generated protofile changes" || echo "No changes to commit"
          git push
