# This workflow is used in order to automatically update go.mod in case one of:
# * osmoutils
# * osmomath
# * x/ibc-hooks
# * x/epochs
# is updated when a push to a branch happens

name: Go Mod Auto Version Update
on: 
  push:
    paths: 
      - osmoutils/**
      - osmomath/**
      - x/ibc-hooks/**
      - x/epochs/**

jobs:
  update_go_mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with: 
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'

      - name: Extract Current Branch
        id: extract_branch
        run: |
          echo "CURRENT_BRANCH=$(echo ${GITHUB_REF} | sed 's|refs/heads/||')" >> $GITHUB_OUTPUT

      # This step fixes a bug, due to which the push to any branch, for example: to person-A/name, triggered this workflow on branch person-b/name,
      # and updated the go.mod on branch person-B/name with commit from branch person-A/name
      - name: Check if the current branch contains commit that triggered the workflow
        id: valid_branch 
        run: |
          CURRENT_BRANCH=${{ steps.extract_branch.outputs.CURRENT_BRANCH }}
          COMMIT_EXISTS_ON=$(echo $(git branch --contains ${{ github.event.after}} ) | grep $CURRENT_BRANCH)

          if [[ "$COMMIT_EXISTS_ON" == *"$CURRENT_BRANCH"* ]];
          then
            echo "VALID=1" >> $GITHUB_OUTPUT
          fi
          
      - name: Run script
        if: ${{ steps.valid_branch.outputs.VALID }} == 1
        run: |
          COMMIT_BEFORE_PUSH=${{ github.event.before }}
          COMMIT_AFTER_PUSH=${{ github.event.after }}
          bash ./scripts/update-go-mod.sh $COMMIT_BEFORE_PUSH $COMMIT_AFTER_PUSH


      - name: Commit changes 
        if: ${{ steps.valid_branch.outputs.VALID }} == 1
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ steps.extract_branch.outputs.CURRENT_BRANCH }}
          commit_message: Update go.mod
