name: Update go.mod

on:
  workflow_dispatch:

jobs:
  update_go_mod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update go.mod
        run: |
          cd osmosis/tests/cl-go-client/
          go get -u github.com/osmosis-labs/osmosis/v16@latest

      - name: Commit and push changes
        run: |
          cd osmosis/tests/cl-go-client/
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add go.mod
          git commit -m "Update go.mod with latest osmosis/v16 dependency"
          git push origin ${{ github.ref }}

      - name: Open pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update go.mod with latest osmosis/v16 dependency
          branch: ${{ github.ref }}
          title: Update go.mod
          body: |
            This pull request updates the `github.com/osmosis-labs/osmosis/v16` dependency in the `go.mod` file to the latest version.
