name: Render and Deploy Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:
    name: Render and deploy protocol and API docs
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Load Rust caching
        uses: astriaorg/buildjet-rust-cache@v2.5.1
      - name: Load get-version action to grab version component of deployment path
        uses: battila7/get-version-action@v2
        id: get_version
      - name: Print version component of deployment path
        run: echo ${{ steps.get_version.outputs.version }}
      - name: Install mdbook
        run: cargo install mdbook mdbook-katex mdbook-mermaid
      - name: Build protocol spec
        run: cd docs/protocol && mdbook build
      - name: Move protocol spec to subdirectory & Deploy
        env:
          DO_DOCS_PK: ${{ secrets.DO_DOCS_PK }}
          DO_DOCS_IP: ${{ secrets.DO_DOCS_IP }}
        run: |
          cd docs/protocol
          if [ -d "do-tmp" ]; then rm -rf do-tmp; fi
          mkdir do-tmp
          mv book do-tmp/${{ steps.get_version.outputs.version }}
          tree do-tmp
          which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )
          which rsync || ( apt-get update -y && apt-get install rsync -y )
          eval $(ssh-agent -s)
          ssh-add <(echo "$DO_DOCS_PK" )
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan $DO_DOCS_IP >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          cd do-tmp/main
          scp -r * root@$DO_DOCS_IP:/var/www/html
