name: Check for TODOs

on:
  pull_request:
    types:
      - closed

jobs:
  scan-for-todos:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
    
    - name: Scan for TODOs
      id: todos
      run: |
        todos=$(git diff ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.merge_commit_sha }} --unified=0 | awk '/^\+.*TODO:/ { sub(/^.*TODO:\s*/, ""); sub(/^ */, ""); $0=toupper(substr($0,1,1)) substr($0,2); print $0 }')
        echo TODOS: $todos
        
        # Set output
        echo "todo_list=$todos" >> $GITHUB_OUTPUT;

    - name: Create GitHub issue for each TODO
      if: steps.todos.outputs.todo_list != ''
      run: |
        # Read TODOs from the output
        IFS=$'\n' read -rd '' -a todos <<< "${{ steps.todos.outputs.todo_list }}"
        
        # Create an issue for each TODO
        for todo in "${todos[@]}"; do
          echo "Creating issue for TODO: $todo"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d '{"title":"$todo","body":"Auto-generated issue triggered by the merge of ${{ github.event.pull_request.html_url }}","assignees":["${{ github.event.pull_request.user.login }}"],"labels":["T:auto"]}'
        done
