name: Update Cosmos SDK Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'SDK version to use'
        required: true
      branch:
        description: 'Branch name in osmosis-labs/cosmos-sdk to fetch the latest commit from'
        required: true
        default: 'main' # Default branch

jobs:
  update-sdk-version-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.20' # Specify your Go version here

      - name: Update SDK Version in Go Mod Files
        run: |
          VERSION="${{ github.event.inputs.version }}"
          echo "Using version: $VERSION"
          MODFILES="./go.mod ./osmoutils/go.mod ./osmomath/go.mod ./x/epochs/go.mod ./x/ibc-hooks/go.mod"
          for modfile in $MODFILES; do
            if [ -e "$modfile" ]; then
              sed -i "s|github.com/osmosis-labs/cosmos-sdk v[0-9a-zA-Z.\-]*|github.com/osmosis-labs/cosmos-sdk $VERSION|g" $modfile
              cd `dirname $modfile`
              go mod tidy
              cd - > /dev/null
            else
              echo "File $modfile does not exist"
            fi
          done
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "auto: update osmosis-labs/cosmos-sdk to $VERSION"
          commit-message: "auto: update osmosis-labs/cosmos-sdk to $VERSION"
          body: |
            **Automated pull request**

            Updating osmosis-labs/cosmos-sdk dependency to the specified version $VERSION.
          base: ${{ github.event.inputs.branch }}
          branch-suffix: random
          delete-branch: true
          assignees: ${{ github.actor }}
          draft: true
          labels: "T:auto,T:code-hygiene,V:state/compatible,no_backport,A:no-changelog"
